// Redirect to the main menu if the game wasn't launched from there
if (!sessionStorage.getItem('gameStarted')) {
  window.location.replace('menu.html');
}

// If coming from the main menu "New Game", reset earnings too
if (localStorage.getItem('newGame')) {
  localStorage.removeItem('earnings');
  localStorage.removeItem('newGame');
  localStorage.setItem('dayNumber',      '1');
  localStorage.setItem('customersToday', '0');
}
// Reset the global happiness timer every time scene 1 loads
localStorage.setItem('gameStartTime', Date.now().toString());

// Scale the game canvas to fit the browser window
function scaleGame() {
  const scale = Math.min(window.innerWidth / 1366, window.innerHeight / 630);
  document.getElementById('scene1').style.transform = `scale(${scale})`;
  document.getElementById('scene2').style.transform = `scale(${scale})`;
  const sat   = document.getElementById('sat-panel');
  const earn  = document.getElementById('earnings-panel');
  const pause = document.getElementById('pause-btn');
  if (sat)   { sat.style.transform   = `scale(${scale})`;  sat.style.transformOrigin   = 'top right';  }
  if (earn)  { earn.style.transform  = `scale(${scale})`; earn.style.transformOrigin  = 'top left';   }
  if (pause) { pause.style.transform = `scale(${scale})`; pause.style.transformOrigin = 'top center'; }
}
window.addEventListener('resize', scaleGame);
scaleGame();

// Apply layout.js config to an element by id
function applyLayout(id, props) {
  const el = document.getElementById(id);
  if (el) Object.assign(el.style, props);
}

applyLayout('customer',    LAYOUT.customer);
applyLayout('bubble',      LAYOUT.bubble);
applyLayout('ticket-wrap', LAYOUT.ticket);
applyLayout('fractions',   LAYOUT.fractions);
applyLayout('confirm-btn', LAYOUT.confirmBtn);
applyLayout('feedback',    LAYOUT.feedback);

// Apply zone size + position from layout.js
document.querySelectorAll('.zone').forEach(zone => {
  Object.assign(zone.style, LAYOUT.zones[zone.dataset.ing]);
});

// Pick a random order (generated by orders.js) and a random customer image
const order = orders[Math.floor(Math.random() * orders.length)];
const customerImg = document.getElementById('customer');
const gender = Math.random() < 0.5 ? 'boy' : 'girl';
customerImg.src = `assets/customer_${gender}.png`;
document.getElementById('scene1').classList.add(gender);

const playerAnswers = {};

// --- Timed reveal ---
setTimeout(() => { customerImg.hidden = false; }, 1500);

setTimeout(() => {
  document.getElementById('order-text').textContent = order.text;
  document.getElementById('bubble').hidden = false;
}, 2500);

setTimeout(() => {
  document.getElementById('ticket-wrap').hidden = false;
  document.getElementById('fractions').hidden = false;
  document.getElementById('confirm-btn').hidden = false;
}, 4000);

// --- Fraction picker ---
let denom = 4;

// Build the fixed 1–10 denominator selector row
const denomRow = document.getElementById('denom-row');
for (let d = 1; d <= 10; d++) {
  const btn = document.createElement('button');
  btn.className = 'denom-btn' + (d === denom ? ' active' : '');
  btn.textContent = d;
  btn.addEventListener('click', () => {
    denom = d;
    denomRow.querySelectorAll('.denom-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    renderFractions();
  });
  denomRow.appendChild(btn);
}

function renderFractions() {
  const container = document.getElementById('frac-buttons');
  container.innerHTML = '';
  for (let n = 1; n <= denom; n++) {
    const btn = document.createElement('button');
    btn.className = 'frac';
    btn.draggable = true;
    btn.dataset.val = `${n}/${denom}`;
    btn.textContent = `${n}/${denom}`;
    btn.addEventListener('dragstart', e => {
      e.dataTransfer.setData('text', btn.dataset.val);
    });
    container.appendChild(btn);
  }
}

renderFractions();

document.querySelectorAll('.zone').forEach(zone => {
  zone.addEventListener('dragover', e => {
    e.preventDefault();
    zone.classList.add('over');
  });
  zone.addEventListener('dragleave', () => zone.classList.remove('over'));
  zone.addEventListener('drop', e => {
    e.preventDefault();
    zone.classList.remove('over', 'correct', 'wrong');
    zone.classList.add('filled');
    const val = e.dataTransfer.getData('text');
    playerAnswers[zone.dataset.ing] = val;
    zone.querySelector('.answer').textContent = val;
  });
});

// --- Confirm button ---
document.getElementById('confirm-btn').addEventListener('click', () => {
  let allCorrect = true;

  document.querySelectorAll('.zone').forEach(zone => {
    const ing = zone.dataset.ing;
    const correct = playerAnswers[ing] === order[ing];
    zone.classList.toggle('correct', correct);
    zone.classList.toggle('wrong', !correct);
    if (!correct) allCorrect = false;
  });

  const fb = document.getElementById('feedback');

  if (allCorrect) {
    fb.textContent = 'Order written!';
    setTimeout(() => {
      // Pass the ticket fractions to scene 2 via localStorage
      localStorage.setItem('lemonadeOrder', JSON.stringify({
        ice: order.ice, lemon: order.lemon, sugar: order.sugar, water: order.water
      }));
      localStorage.setItem('gender', gender);
      window.location.href = 'scene_2.html';
    }, 1500);
  } else {
    fb.textContent = 'Try again!';
  }
});
